### ISSUE TITLE
server

### ISSUE THREAD

**Issue by DRA615** [Elemend/Vein-Miner-Unified-1.15#2]
I am having issues using vein-miner in a server. I can use it in single world but not on server.

**Comment by Elemend** [comment]
can you pinpoin the Issue to something specific? Is there some kind of output log for the server that maybe shows errors? Does the server unload the chunk at the worldborder? Is the gamerule commandchainlength set to 65536? Are command blocks even enabled?

**Comment by DRA615** [comment]
Commandchainlength is set to 65536, and Command Blocks are enabled. I created a world on single player and uploaded it to Minecraft Realms to share with friends. When i try to use the already enchanted items it doesn't work. Meaning when i shift it doesn't Vein mine. It wont even let me enchant new items. I have even tried turning the enchantment table off and Vein Mine still wont work. I hope this is helpful, and i appreciate you looking into this.

**Comment by Elemend** [comment]
This might actually be a bug. [REALMS-1805](https://bugs.mojang.com/browse/REALMS-1805) Could be that the predicate files aren't recognised or something.

**Comment by DRA615** [comment]
Thank you for the information. 

I have other data packs that i am using and the only one not working is this one. 

This is a really COOL! Data Pack Thanks for putting it together and sharing it :)

**Comment by TheSofas** [comment]
@Elemend You are correct. The predicates aren't moved and are tagged as "unused". Here's an upload log from trying to upload it to realms.

https://pastebin.com/1WMUSGUR

**Comment by 123Pixely** [comment]
i'm having the same problem when its on a realm it wont work

**Comment by Elemend** [comment]
That Bug was fixed, so it should work now.
