### ISSUE TITLE
Server (Not Realm

### ISSUE THREAD

**Issue by Cloutan** [Elemend/Vein-Miner-Unified-1.15#3]
I have been looking for veinminer and just found out about this. I put the file I got from my download into the "datapacks" folder on the website. The custom commands (/function vm/...) were there so it was installed properly yet veinminer just doesn't seem to work.

**Comment by Elemend** [comment]
Is this server modded in any way? Do you have some kind of server log in which there are errors or warnings?
_I sure hope you didn't forget you have to crouch while mining a block._
