### ISSUE TITLE
The enchantment option disables veinmining

### ISSUE THREAD

**Issue by benoit-dubreuil** [Elemend/Vein-Miner-Unified-1.15#4]
If the enchantment option is enabled, it disables veinmining.

**Comment by Elemend** [comment]
Does this Issue happen to you over time or right from the start? I couldn't recreate this, unfortunately.

**Comment by benoit-dubreuil** [comment]
Right from the start.

Steps :

1. Create a new world.
2. Play the new world.
3. Quit the new world.
4. Download and the veinmine datapack into the right folder.
5. Call the `/reload` function just in case.
6. Notice in the achievements that the datapack exists.
7. Call the `/function vm:custom` function.
8. Enable the enchantments, disable the hunger and enable the teleportation.
9. Crouch an mine coal with a steel pickaxe.
10. Notice that it does not veinmine the coal blocks.

**Comment by Elemend** [comment]
Then I would need to know what a steel pickaxe is? If it's from a mod then of course it doesn't work and I can't help. If it's a redesigned iron pickaxe from another datapack it should work. If it's a stone pickaxe of course it won't work.

**Comment by benoit-dubreuil** [comment]
Woops, I mean an iron pickaxe, sorry. I only use 3 datapacks : veinminer, treecapacitor and an autoplanter.

**Comment by Elemend** [comment]
No Idea what to do about it.
