### ISSUE TITLE
Block limit

### ISSUE THREAD

**Issue by blindisde84** [Elemend/Vein-Miner-Unified-1.15#5]
Is there any way to edit how many blocks it will break when you use veinminer? I am trying to get it closer to 128 maximum broken.

**Comment by Elemend** [comment]
yes. open the datapack and find the file under `vm:unbreaking/calcdur`
In there you'll see these two lines:
`scoreboard players operation @s vm_break >< @s vm_calc`
`scoreboard players operation @s vm_break -= @s vm_calc`
Add another one that says this:
`execute if score @s vm_break matches 2.. run scoreboard players set @s vm_break 128`
That should do it.

**Comment by blindisde84** [comment]
That worked, one more, what if I want to change the area it breaks, say 3x3x3

**Comment by blindisde84** [comment]
Woukd it be the vm_proc xyz?

**Comment by Elemend** [comment]
it would be the function `vm:fill/block_xyz` 
I use the "positioned" argument and "if blocks". You would need to lower the numbers of the relative positions and the dx/y/z selectors to go down to roughly 3x3x3.
And I think I made a mistake with that first command; The score is the durability. and it makes more sense to say "if the durability would allow for more than 128 blocks, set it to 128"
so this is better:
`execute if score @s vm_break matches 128.. run scoreboard players set @s vm_break 128`

**Comment by blindisde84** [comment]
Thank you that should solve it all!

**Comment by blindisde84** [comment]
What exactly would I change in the lines "execute if score @s vm_break matches 2.. align xyz positioned ~-4 ~-4 ~-4 if entity @e[type=area_effect_cloud,tag=vm_getpos,sort=nearest,limit=1,dx=8,dy=8,dz=8] if blocks ~5 ~4 ~4 ~5 ~4 ~4 -29999986 1 7777 all positioned ~5 ~4 ~4 run function vm:fill/block_xyz"

**Comment by blindisde84** [comment]
If I understand correctly if I want to do 2x2x2 would I have to take the difference of 6 and subtract it from the if position is ~-4 ~-4 ~-4 and change that to ~-10 ~-10 ~-10?

**Comment by Elemend** [comment]
I guess what I meant with lower numbers is not further into the negatives. A short explanation may help: in the example the position shifts 4 blocks into the negative directions, then back 4 blocks, but in the positive x-direction you go one further. For your example I think you would need to go back 1 block into the negative directions, and then one back, but in the x-direction you would go 2 back. And the dx-selector would be 2 I think.
